In [4]:
import numpy as np

In [5]:
lista = [1, 2, 3, 4, 5]

array = np.array(lista)

In [6]:
print(lista)
print(array)



[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [7]:
arr_zeros = np.zeros(10)

print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
matriz_zeros = np.zeros((7, 5))
print(matriz_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [9]:
lista_de_notas = [9.9, 8.6, 7.9, 4.5]

notas = np.array(lista_de_notas)

In [12]:
print('Maximo', notas.max())
print('Minimo', notas.min())
print('Desvio Padrão', notas.std())
print('Media', notas.mean())
print('Posiçao notas', notas.argmin())



Maximo 9.9
Minimo 4.5
Desvio Padrão 1.995463605280738
Media 7.725
Posiçao notas 3


In [19]:
pergunta = int(input("Fala uma nota ae"))

if pergunta >= 5 :
    print("passooour nega")
else:
    print("quaequaequaeeee! errooou!")



Fala uma nota ae 10


passooour nega
